<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="inboxPage.aspx.cs" Inherits="db_a27401_asp.inboxPage" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Inbox</title>
    <style type="text/css">
        .status_style  {
                
          width:260px;
          height:auto;
          padding:10px;
          background-color:#ffffff;
          border: 4px solid white ;
          margin: 5px;
        }
        .msg_L_style  {       
          width:260px;
          height:auto;
          padding:10px;
          background-color:#e6f2ff;
          border: 2px solid white ;
          margin: 4px;
        }
        .msg_R_style  {
               
          width:260px;
          height:auto;
          padding:10px;
          background-color:#e6f2ff;
          border: 2px solid white ;
          margin: 4px;
          text-align:right;
          margin-left: 140px;
        }

        .auto-style1 {
            width: 607px;
        }
        .auto-style2 {
            width: 438px;
        }
        .auto-style3 {
            height: 23px;
        }
        .auto-style4 {
            width: 438px;
            height: 23px;
        }
        .auto-style5 {
            height: 24px;
        }
        .auto-style6 {
            width: 438px;
            height: 24px;
        }
        .auto-style9 {
            width: 271px;
        }
        #Button1 {
        }
        .auto-style16 {
            width: 127px;
        }
        .auto-style18 {
            height: 23px;
            width: 127px;
        }
        .auto-style19 {
            height: 24px;
            width: 127px;
        }
        .auto-style20 {
            width: 438px;
            height: 376px;
        }
        .auto-style21 {
            width: 127px;
            height: 376px;
        }
        .auto-style22 {
            height: 376px;
        }
        .auto-style23 {
            width: 438px;
            height: 16px;
        }
        .auto-style24 {
            height: 16px;
            width: 127px;
        }
        .auto-style25 {
            height: 16px;
        }
        .auto-style26 {
            width: 438px;
            height: 30px;
        }
        .auto-style27 {
            width: 127px;
            height: 30px;
        }
        .auto-style28 {
            height: 30px;
        }
    </style>
    <script src="Scripts/jquery-1.10.2.min.js" ></script>
    <!--Reference the SignalR library. -->
    <script src="Scripts/jquery.signalR-2.0.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="signalr/hubs"></script>
    <script type="text/javascript">


        
        $(function () {

            var chat = $.connection.myHub1;
            var UserToVar = $('#UserTo').html();
            var UserFromVar = $('#UserFrom').html();
            
            $('#MsgArea').scrollTop($('#MsgArea')[0].scrollHeight); // for auto scrolling down on page load
            //alert(UserFromVar);

            $.connection.hub.qs = { "userName": UserFromVar };
            
            // Function: "upadateMessae" will be called on the browsers of other global clients
            //Values for this function: "UserFrom, MessageStirng" will come from server
            chat.client.updateMessage = function (UserFrom, MessageStirng) {

                //var msgUserPage = $('#<%=UserTo.ClientID%>').val();
                //alert(msgUserPage);
                //alert(UserFrom);
                //alert(UserToVar);


                if (UserFrom == UserToVar) { // not to update the message box if the client is in other user's message page
                    var currentdate = new Date();
                    var datetime = currentdate.getHours() + ":"
                                        + currentdate.getMinutes() + ":"
                                        + currentdate.getSeconds() + " , "
                                        + currentdate.getDate() + "/"
                                        + (currentdate.getMonth() + 1) + "/"
                                        + currentdate.getFullYear();


                    $('#MsgArea').append("<div class=\"msg_L_style\">" + UserFrom +
                        ": " + MessageStirng + "<br/>" + datetime + "</div>");
                    $('#MsgArea').scrollTop($('#MsgArea')[0].scrollHeight);
                }
                else { }
                
            };

            // Function that will be called on the browser of local client
            $.connection.hub.start().done(function () {
                
                $('#MsgReplyButton').click(function () {

                    var currentdate = new Date();
                    var datetime = currentdate.getHours() + ":"
                                    + currentdate.getMinutes() + ":"
                                    + currentdate.getSeconds()+" , "
                                    +currentdate.getDate() + "/"
                                    + (currentdate.getMonth() + 1) + "/"
                                    + currentdate.getFullYear();
                                    
                    // Initiating Ajax and other server methods

                    /////////////////////////////////////////////////////////////////////////////
                    //////////////////// convert to string otherwise trouble ////////////////////
                    /////////////////////////////////////////////////////////////////////////////

                    ajaxPostMsg(UserFromVar, UserToVar, String($('#<%=MsgTextBox.ClientID%>').val()));
                    chat.server.broadcastMessage(String(UserFromVar), String(UserToVar), String($('#<%=MsgTextBox.ClientID%>').val()));

                    // local browser operations

                    $('#MsgArea').append("<div class=\"msg_R_style\">" +
                        UserFromVar + ": " + String($('#<%=MsgTextBox.ClientID%>').val())+
                        "<br/>" + datetime + "</div>");

                    $("#<%=MsgTextBox.ClientID%>").val("");
                    $('#MsgArea').scrollTop($('#MsgArea')[0].scrollHeight);
                });
            });
        });

        // Ajax method for database operations
        function ajaxPostMsg(userFROM,userTO,msgTEXT) {
            $.ajax({
                type: 'POST',
                url: 'inboxPage.aspx/sendMessageToDb',//make "CheckUser" lower case or it won't work!!!!!
                data: JSON.stringify({ userFrom:userFROM,userTo: userTO,msgText:msgTEXT }),
                contentType: 'application/json; charset=utf-8',
                dataType: 'json',
                success: function (msg) {

                    //alert(msg.d);
                }
            });

        }

    </script>
</head>
<body>
    <form id="form1" style="width:100%;height:100%;padding:10%; background-color:#e6f7ff;" runat="server" >
    
        
        <table class="auto-style1" style="width:80%;height: 80%; background-color:#EBEBE0;">
                <tr>
                    <td class="auto-style9" rowspan="14" style="vertical-align:top;" >
                        <asp:HyperLink ID="ToNewsfeed" runat="server" ImageHeight="20px" ImageUrl="icon_images/icon_newsfeed.png" ImageWidth="20px" NavigateUrl="loggedIn.aspx"></asp:HyperLink>
                        <asp:HyperLink ID="ToNewsfeedText" runat="server" NavigateUrl="~/loggedIn.aspx">Newsfeed</asp:HyperLink>
                        <br />
                        <br />
                        <asp:Button ID="NewMsgButton"  OnClick="NewMsgButton_Click"  Text="New Message" runat="server" Height="23px" Width="96px" style="margin-top: 2px" />
                        <br />
                        <br />
                         Previous conversations<br />
                        <asp:Panel ID="PreConvArea" runat="server" Height="559px" ScrollBars="Vertical">
                        </asp:Panel>
                        <br />
                    </td>
                    <td class="auto-style2" rowspan="2">
                        <br />
                        <br />
                        Conversation with:
                        <asp:Label ID="UserTo" ClientIDMode="Static" runat="server"></asp:Label>

                        <!--.///////////////////////////////.Hidden div for user names//////////////////////////// .-->

                        <div id="UserFrom" style="width: 99px;display: none" runat="server" >
                        </div>
                    </td>
                    <td class="auto-style16">
                        &nbsp;<a href="loggedIn.aspx"><img alt="" src="/icon_images/icon_notification.png" style="height: 24px; width: 26px; margin-top: 4px" id="notification_image" /></a>&nbsp;&nbsp; <a href="loggedIn.aspx" ><img alt="icon_images" src="icon_images/icon_friendrequest.png" style="height: 23px; width: 22px" id="photo_image0" /></a></td>
                    <td class="auto-style76">
                        <asp:Button ID="LogoutButton" Text="Log out" OnClick="LogoutButton_ClickMethod" runat="server" Height="23px" style="margin-top: 0px" Width="59px" />
                    </td>
                </tr>
                <tr>
                    <td class="auto-style16">
                        <asp:Button ID="ProfileButton" runat="server" Text="Button" Width="120px" />
                        </td>
                    <td></td>
                </tr>
                <tr>
                    <td class="auto-style20">

                        <asp:Panel ID="MsgArea" runat="server" BackColor="White" BorderColor="#CCFFFF" Height="360px" ScrollBars="Vertical" style="margin-top: 0px" Width="445px">
                        </asp:Panel>

                    </td>
                    <td class="auto-style21">
                        </td>
                    <td class="auto-style22"></td>
                </tr>
                <tr>
                    <td class="auto-style23">
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <asp:TextBox ID="MsgTextBox" ClientIDMode="Static" runat="server" Height="61px" Width="264px" TextMode="MultiLine" style="margin-left: 0px"></asp:TextBox>
                    </td>
                    <td class="auto-style24"> 
                    </td>
                    <td class="auto-style25"></td>
                </tr>
                <tr>
                    <td class="auto-style26"> 
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; <asp:FileUpload ID="PostFileUploadBox" runat="server" style="margin-bottom: 0px" /> 
                    </td>
                    <td class="auto-style27"> 
                        </td>
                    <td class="auto-style28"></td>
                </tr>
                <tr>
                    <td class="auto-style2">
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <input id="MsgReplyButton" style="width: 69px" type="button" value="Reply" /></td>
                    <td class="auto-style16"></td>
                    <td class="auto-style76"></td>
                </tr>
                <tr>
                    <td class="auto-style4">
                        </td>
                    <td class="auto-style18"></td>
                    <td class="auto-style3"></td>
                </tr>
                <tr>
                    <td class="auto-style2">
                        &nbsp;</td>
                    <td class="auto-style16"></td>
                    <td class="auto-style108"></td>
                </tr>
                <tr>
                    <td class="auto-style6"></td>
                    <td class="auto-style19"></td>
                    <td class="auto-style5"></td>
                </tr>
                <tr>
                    <td class="auto-style2">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </td>
                    <td class="auto-style16"></td>
                    <td class="auto-style81"></td>
                </tr>
                <tr>
                    <td class="auto-style2">&nbsp;
                        
                    </td>
                    <td class="auto-style16"></td>
                    <td class="auto-style82"></td>
                </tr>
                <tr>
                    <td class="auto-style2"></td>
                    <td class="auto-style16"></td>
                    <td class="auto-style81"></td>
                </tr>
                <tr>
                    <td class="auto-style2">&nbsp;</td>
                    <td class="auto-style16">&nbsp;</td>
                    <td class="auto-style109">&nbsp;</td>
                </tr>
                <tr>
                    <td class="auto-style2">&nbsp;</td>
                    <td class="auto-style16">&nbsp;</td>
                    <td class="auto-style109">&nbsp;</td>
                </tr>
            </table>
        
        <p>
            &nbsp;</p>
        <p>
            &nbsp;</p>
        <p>
            &nbsp;</p>
    </form>
</body>
</html>
